name: Java CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      run: mvn package
    - name: Upload to sonar
      env:
        SONAR_SERVER_URL: ${{ secrets.SONAR_SERVER_URL }}
        SONAR_AUTH_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
      run: mvn sonar:sonar --settings settings.xml
    - name: Upload to repository
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
      run: mvn deploy --settings settings.xml
